# version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:80"
    environment:
      - CORS_ORIGINS=http://35.78.101.190:3000


  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend